import Head from 'next/head';
import { HoverableGallery } from 'features/hoverable_gallery';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <HoverableGallery />
      </main>
    </>
  );
}
